PROJECT_ROOT = $$PWD

DESTDIR = $$PROJECT_ROOT/build
PROJECTFILENAME = $$basename( _PRO_FILE_ )
OBJECTS_DIR = $$DESTDIR/.obj/$$PROJECTFILENAME
MOC_DIR = $$DESTDIR/.moc/$$PROJECTFILENAME
UI_DIR = $$DESTDIR/.ui/$$PROJECTFILENAME
RCC_DIR = $$DESTDIR/.res/$$PROJECTFILENAME
